use retaildb_timeseries_staging_myeyedr
go

declare @comps table (home_company varchar(100), away_company varchar(100), strength float)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Accurate Optical',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Accurate Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'ACUVUE',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'ACUVUE',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'ALLEGANY OPTICAL',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'ALLEGANY OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'AMERICA''S BEST CONTACTS & EYEGLASSES',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'AMERICA''S BEST CONTACTS & EYEGLASSES',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'BJ''s OPTICAL',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'BJ''s OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'cambridge Eye Doctors',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'cambridge Eye Doctors',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'COSTCO OPTICAL',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'COSTCO OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'DOCTOR''S VALUVISION',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'DOCTOR''S VALUVISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Dr. Bizer''s VALU VISION',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Dr. Bizer''s VALU VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'DR. Bizer''s VISIONWORLD',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'DR. Bizer''s VISIONWORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'EYE DRx',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'EYE DRx',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'EYEMASTERS',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'EYEMASTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'HOUR EYES',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'HOUR EYES',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'LENSCRAFTERS',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'LENSCRAFTERS',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'myeyeDr.',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'myeyeDr.',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Optometrists and Insurance Companies',0)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'PEARLE VISION',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'PEARLE VISION',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Sam''s CLUB Optical',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Sam''s CLUB Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Sears Optical',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Sears Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'SHAMIR',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'SHAMIR',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Sterling OPTICAL',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Sterling OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'TARGET Optical',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'TARGET Optical',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Total Vision Care',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Total Vision Care',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'UNITED OPTICAL',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'UNITED OPTICAL',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'VISION WORLD',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'VISION WORLD',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'Visionworks',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'Visionworks',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'VOORTHUIS OPTICIANS',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'VOORTHUIS OPTICIANS',1)
insert into @comps(home_company, away_company, strength) VALUES('Accurate Optical', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('ACUVUE', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('ALLEGANY OPTICAL', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('AMERICA''S BEST CONTACTS & EYEGLASSES', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('BJ''s OPTICAL', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('cambridge Eye Doctors', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('COSTCO OPTICAL', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('DOCTOR''S VALUVISION', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Dr. Bizer''s VALU VISION', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('DR. Bizer''s VISIONWORLD', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('EYE DRx', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('EYEMASTERS', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('HOUR EYES', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('LENSCRAFTERS', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('myeyeDr.', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Optometrists and Insurance Companies', 'WALMART VISION CENTER',0)
insert into @comps(home_company, away_company, strength) VALUES('PEARLE VISION', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Sam''s CLUB Optical', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Sears Optical', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('SHAMIR', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Sterling OPTICAL', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('TARGET Optical', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Total Vision Care', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('UNITED OPTICAL', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('VISION WORLD', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('Visionworks', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('VOORTHUIS OPTICIANS', 'WALMART VISION CENTER',1)
insert into @comps(home_company, away_company, strength) VALUES('WALMART VISION CENTER', 'WALMART VISION CENTER',1)


insert into weighed_competitive_weights(home_company_id, away_company_id, strength)
select 
	ch.company_id as home_company_id,
	ca.company_id as away_company_id,
	c.strength
from @comps c
inner join companies ch on ch.name = c.home_company
inner join companies ca on ca.name = c.away_company